language: python

python:
- '2.7'
- '3.5'

install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt

script:
- nosetests -v --with-coverage --cover-package=woodstove --cover-inclusive

deploy:
  provider: pypi
  user: richardmarshall
  password:
    secure: p64uPRQ1nEXP+EQubcOtqEg6xJ2rNqTfTFLR6xNNUuuCTVVMCuCZvqOZWIuCJX1bzIYsYozvYVSl1gdHqKNzyKo7GSLvHPZCMi+a88Pp0OxRWKkiyG65qUB1Y/aNmJdOE8Xuzeb6/JxG8GpvOMi7Qx6pkI7zwRM0sim9z4k3+HXJHmuOlaN2Sxy2l5ClXK1CTZaykF8OxF/tbpkDNY1TyfdSa15bV7pBzelvxV9olngXTqy0ieuMaENce+tLRlZ1PH/oQoC7dDeGRBDTwaqg8w4jIWuZ9g0kWoYBhXSkUomfFxW7vmEXdBO03P3yqqbPE+38yH6wooUZjkNbwVtC/FvyJ+CulE4BdWjKQDs3Fa6EOvd4TZUiAe9sz+L3ZMQ4qnclLkFlhUMSME4NrIPAvjTubZkeid0soEM97dY6xyX0CbJu7ZICTg2hDH+PWuwqEcTRDm0En2e2hS1HVZVU/aR41c0leBzz3xUTJ/CfCMEKrRDRrxELoeHAHyBg9WpT1fFAhgH7ScyXTKzsdR6ahvDOoALNc8nd5XLan6QL8/GTzTdHFAP/hvX9d+6umT4aWKPfxvHukgGZT+8BqM0Eg6fmSMGJ8JuqZQZG1Yz7/W7Z6lRrOyvGF2hr0W6MFyBLKHDdJputasyLu3KDCrdW8GeVt1Nj4/vW81elx+oyWZo=
  on:
    tags: true
